### ISSUE TITLE
alpine3.14+ fails when using Docker in Docker in Ruby

### ISSUE THREAD

**Issue by luke-hill** [alpinelinux/docker-alpine#237] opened 2022-03-01 14:06 UTC
The following dockerfile only works (DinD) when being used with alpine 3.13 and **below** (This is an issue for ruby 3.1.1, as this doesn't have an alpine 3.13 version).

```
FROM ruby:3.1.1-alpine3.15

ENV BUNDLER_VERSION=2.3.6 \
    BUNDLE_PATH=/app/vendor/bundle

RUN apk add --no-cache --update build-base bash jq curl libffi-dev

RUN mkdir -p /app

WORKDIR /app

RUN gem install bundler -v $BUNDLER_VERSION
```

**Comment by ncopa** [comment] 2022-03-17 12:16
I cannot reproduce it due to I dont have any `Gemfile*` here:
```
...
Step 5/11 : COPY Gemfile* /app/
COPY failed: no source files were specified
```

**Comment by ncopa** [comment] 2022-03-17 12:20
what kernel version (`uname -a`) and docker version (`docker info`) do you use?

I suspect you have a buggy docker or libseccomp version. See
https://wiki.alpinelinux.org/wiki/Release_Notes_for_Alpine_3.14.0#faccessat2

**Comment by luke-hill** [comment] 2022-03-17 13:03
I've edited down the file and also added this to moby/moby

**Comment by ncopa** [comment] 2022-03-29 11:01
As I mentioned in https://github.com/alpinelinux/docker-alpine/issues/237#issuecomment-1070855160 and as @thaJeztah confirmed in https://github.com/moby/moby/issues/43311#issuecomment-1061040432, this is a bug in docker and libseccomp which is fixed in latest releases.

There is nothing more we can do on alpine side to fix this.

**Closed by ncopa** 2022-03-29 11:01 UTC
